<?php

namespace Database\Factories;

use App\Models\Customer;
use App\Modules\ASCM\Models\SupportCase;
use Illuminate\Database\Eloquent\Factories\Factory;

class SupportCaseFactory extends Factory
{
    protected $model = SupportCase::class;    

    public function definition(): array
    {
        $status = fake()->randomElement(['pending', 'open', 'resolved', 'closed']);

        return [
            // case_number is auto-generated by SupportCase::booted() if left null.
            'customer_id' => Customer::factory(),
            'category' => fake()->randomElement(['Technical', 'Returns', 'Warranty', 'Support', 'Billing']),
            'priority' => fake()->randomElement(['low', 'medium', 'high', 'critical']),
            'status' => $status,
            'sla_due_at' => fake()->dateTimeBetween('now', '+5 days'),
            'resolved_at' => in_array($status, ['resolved', 'closed']) ? fake()->dateTimeBetween('-2 months', 'now') : null,
            'closed_at' => $status === 'closed' ? fake()->dateTimeBetween('-1 month', 'now') : null,
        ];
    }

    public function status(string $status): static
    {
        return $this->state(fn () => ['status' => $status]);
    }
}
