<?php

namespace Database\Factories;

use App\Models\Customer;
use App\Modules\ASCM\Models\WarrantyRegistration;
use App\Modules\ASCM\Models\WarrantyClaim;
use Illuminate\Database\Eloquent\Factories\Factory;

class WarrantyClaimFactory extends Factory
{
    protected $model = WarrantyClaim::class;

    public function definition(): array
    {
        $status = fake()->randomElement(['submitted', 'under_review', 'approved', 'rejected']);
        $estimated = fake()->randomFloat(2, 20, 900);

        return [
            // claim_number is auto-generated by WarrantyClaim::booted() if left null.
            'warranty_registration_id' => WarrantyRegistration::factory(),
            'customer_id' => Customer::factory(),
            'issue_description' => fake()->randomElement([
                'Device won\'t power on after normal use.',
                'Screen flickers intermittently.',
                'Battery no longer holds a charge.',
                'Unit arrived with a cracked housing.',
                'Keyboard keys unresponsive.',
            ]),
            'requested_action' => fake()->randomElement(['repair', 'replace', 'refund', 'credit']),
            'estimated_amount' => $estimated,
            'approved_amount' => $status === 'approved' ? $estimated : null,
            'status' => $status,
            'decision_at' => in_array($status, ['approved', 'rejected']) ? fake()->dateTimeBetween('-1 month', 'now') : null,
        ];
    }

    public function status(string $status): static
    {
        return $this->state(fn () => ['status' => $status]);
    }
}
